### ISSUE TITLE
Login Welcome Page

### ISSUE THREAD

**Issue by EmirVelazquez** [graysonm23/Taste-Buds#5]
User will be greeted by "Welcome to Taste Buds "
-Animation
-Button to Submit and hide Welcome form
-User input form: 
    - Criteria: User should be able to enter a food dish in the search  box 
    - Criteria: User should be able to click on the search button 
    - Criteria: User should not be able to hit submit button if there is no text in search bar

**Comment by graysonm23** [comment]
created welcome page and pushed to my branch.

**Comment by graysonm23** [comment]
done
